version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -t ./package
  pre_build:
    commands:
      - python -m unittest test.test
  build:
    commands:
      - chmod +x ./mecab-service/local/libexec/mecab/mecab-dict-index
      - export PATH=${PWD}/mecab-service/local/bin:$PATH
      - export LD_LIBRARY_PATH=${PWD}/mecab-service/local/lib:$LD_LIBRARY_PATH
      - ./mecab-service/local/libexec/mecab/mecab-dict-index -d ./mecab-service/local/lib/mecab/dic/ipadic -u user.dic -f utf-8 -t utf-8 ./user.csv
artifacts:
  files:
    - main.py
    - package/*
    - mecab-service/*
  name: function.zip
  discard-paths: no
