AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Resources:
  MecabApiFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: 
        S3Bucket: code-build-output-mecabapi
        S3Key: MecabApi.zip
      FunctionName: MecabApi
      Handler: main.handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/lambda_basic_execution'
      Runtime: python3.7
      Timeout: 30
    DeletionPolicy: Retain