version: 2
jobs:
  deploy:
    docker:
    - image: kroniak/ssh-client:3.9
    working_directory: /home/circleci/project
    steps:
    - add_ssh_keys:
        fingerprints:
        - ${SSH_KEY}
    - run:
        name: pull
        command: |
          mkdir ~/.ssh/ && echo -e "Host ${HOST_NAME}\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          ssh ${SSH_USER}@${HOST_NAME} "cd ~/throwtrash-compare && git pull origin master"
    - run:
        name: download_trained_data
        command: |
          ssh ${SSH_USER}@${HOST_NAME} "cd ~/throwtrash-compare/app/dataset && aws s3 cp s3://throwtrash-compare/20210101/word2vec.gensim.model.tar.bz2 ./ && tar jxfv word2vec.gensim.model.tar.bz2"
    - run:
        name: restart
        command: |
          ssh ${SSH_USER}@${HOST_NAME} "cd ~/throwtrash-compare/deploy && chmod +x deploy.sh && ./deploy.sh"
workflows:
  version: 2
  release:
    jobs:
    - deploy
