
version: "3"
services:
    compare:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../:/app:cached
        ports: 
            - 8888:8888
            - 8000:8000
        command: /bin/sh -c "while sleep 1000; do :; done"